kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: backend
    component: backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: expense
      tier: backend
      component: backend
  template:
    metadata:
      labels:
        project: expense
        tier: backend
        component: backend
    spec:
      containers:
      - name: backend
        image: hussainbi/backend:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: backend
                
