kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    project: expense
    tier: backend
    component: backend
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080