kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:  
  selector:
    project: expense
    env: dev
    component: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    env: dev
    component: backend
spec:
  containers:
  - name: nginx
    image: nginx        