kind: Replicaset
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: expense
    env: uat
spec:
  replicas: 4
  selector:
    matchLabels:
      project: expense
      env: uat
  template:
    metadata:
      labels:
        project: expense
        env: uat 
    spec:
      containers:
      - name: nginx
        image: nginx
               
    

    