kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: expense
    env: uat
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      env: uat
  template:
    metadata:
      labels:
        project: expense
        env: uat  
    spec:
      containers:
      - name: nginx
        image: hussainbi/deploy:1.0           