kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    env: dev
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      env: dev
      component: db
  template:
    metadata:
      labels:
        project: expense
        env: dev
        component: db
    spec:
      containers:
      - name: mysql
        image: hussainbi/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector: # labels are used as selectors
    project: expense
    env: dev
    component: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306                
