apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---  
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      tier: backend
      component: backend
  template:
    metadata:
      labels:
        project: expense
        tier: backend
        component: backend
    spec:
      containers:
      - name: backend
        image: hussainbi/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend

---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    project: expense
    env: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080                
