apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  nodeSelector:
      topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"