apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app-name: pod-3
spec:
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  labels:
    app-name: pod-4
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - pod-3
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"